import Head from 'next/head';
import { getLatestPosts } from '../lib/api';
import { useState } from 'react';

export default function Home({ latestPosts: { edges } }) {
  const [toggleViewMode, setToggleViewMode] = useState(false);
  return (
    <>
      <Head>
        <title>NextJs WordPress</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex justify-end p-5'>
        <button
          className='px-4 py-2 font-bold text-white bg-blue-500 rounded-full hover:bg-blue-700'
          onClick={() => setToggleViewMode(!toggleViewMode)}
        >
          {toggleViewMode ? 'grid' : 'list'}
        </button>
      </div>
      <div className={`grid grid-cols-${toggleViewMode ? '1' : '3'} gap-4 p-5`}>
        {edges.map((post) => (
          <div
            className='mx-2 my-2 overflow-hidden rounded shadow-lg '
            key={post.node.id}
          >
            <img
              className='w-full'
              src={post.node.featuredImage?.node.sourceUrl}
              alt={post.node.title}
            />
            <div className='px-6 py-4'>
              <div className='mb-2 text-xl font-bold'>{post.node.title}</div>
              <div
                className='text-base text-grey-darker'
                dangerouslySetInnerHTML={{ __html: post.node.excerpt }}
              ></div>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const latestPosts = await getLatestPosts();
  return {
    props: { latestPosts },
  };
}
